language: node_js
node_js:
  - "8"

before_install:

install:
  - cd web && npm install

script:
# your build process
  - npm test

branches:
  only:
# the source branch
    - master

cache:
  directories:
    - web/node_modules
